BEGIN;

CREATE TYPE work_status AS ENUM ('completed', 'failed');

CREATE TABLE worker (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(255) NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    interval INT NOT NULL
);

CREATE TABLE work (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    worker_id INT NOT NULL REFERENCES worker(id) ON DELETE CASCADE,
    scheduled_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE work_log (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    work_id INT NOT NULL REFERENCES work(id) ON DELETE CASCADE,
    status work_status NOT NULL,
    message VARCHAR(255) NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration INT NOT NULL
);

COMMIT;
