services:
  postgres:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pL5dT78Uyu
        POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - database-postgres:/var/lib/postgresql/data
    
volumes:
  database-postgres: