name: gather-it

services:
  webapi:
    build:
      context: ../gatherIt
      dockerfile: WebApi/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      postgres-jobads:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
        # for now webapi registers itself with scheduler so JustJoinIt and TheProtocol endpoints can be used to gather data
        # this will change when appropriate scrapers will be implemented
      scheduler:
        condition: service_healthy
    environment:
      - Scheduler__Url=http://scheduler:8101/register
      - Scheduler__WorkerEndpoint=http://webapi:8001/api/Comulator/Download
      - ASPNETCORE_URLS=http://+:8001

  gatherit:
    build:
      context: ../Comulator
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://rabbituser:rabbitpass@rabbitmq:5672/%2f
      - KAFKA_URL=kafka:9092

  postgres-jobads:
    build:
      context: ../Database
      dockerfile: Dockerfile-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pL5dT78Uyu
      POSTGRES_DB: postgres
    ports:
      - "5400:5432"
    volumes:
      - database-postgres-jobads:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-scheduler:
    build:
      context: ../scheduler/database
      dockerfile: Dockerfile-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jad21D10cazX
      POSTGRES_DB: postgres
    ports:
      - "5401:5432"
    volumes:
      - database-postgres-scheduler:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  scheduler:
    build:
      context: ../scheduler
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    depends_on:
      postgres-scheduler:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:jad21D10cazX@postgres-scheduler:5432/postgres
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://127.0.0.1:8101/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  pracuj-scraper:
    build:
      context: ../scrapyard/pracuj-scraper
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    depends_on:
      rabbitmq:
        condition: service_healthy
      scheduler:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://rabbituser:rabbitpass@rabbitmq:5672/%2f
      - RABBITMQ_EXCHANGE=mapping_exchange
      - RABBITMQ_ROUTING_KEY=mapping
      - SCHEDULER_URL=http://scheduler:8101/register
      - SCRAPER_ENDPOINT=http://pracuj-scraper:8800/scrap
      - ASPNETCORE_URLS=http://+:8001
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://127.0.0.1:8800/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  binder:
    build:
      context: ../binder
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-jobads:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://rabbituser:rabbitpass@rabbitmq:5672/%2f
      - RABBITMQ_QUEUE_NAME=MappingQueue
      - RABBITMQ_CONSUMER_TAG=binder
      - DATABASE_URL=postgres://postgres:pL5dT78Uyu@postgres-jobads:5432/postgres
      - RUST_LOG=info

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
      RABBITMQ_DEFINITIONS_FILE: "/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database-postgres-jobads:
  database-postgres-scheduler:
  rabbitmq-data:
