services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: ../Comulator
      dockerfile: WebApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - postgres
      - rabbitmq

  descriptionservice:
    build:
      context: ../DescriptionService
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - webapi
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbituser:rabbitpass@rabbitmq:5672/
      - WEBAPI_URL=http://webapi:8080/

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pL5dT78Uyu
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - database-postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
      RABBITMQ_DEFINITIONS_FILE: "/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

volumes:
  database-postgres:
  rabbitmq-data:
