name: gather-it

services:
  jobReadApi:
    image: gather-it-jobreadapi:latest
    build:
      context: ../JobReadApi
      dockerfile: JobReadApi.WebApi/Dockerfile
    ports:
      - "8002:8080"
    depends_on:
      postgres-jobads:
        condition: service_healthy
    environment:
      - DB_CONNECTION_STRING=Host=postgres-jobads;Port=5432;Database=postgres;Username=postgres;Password=pL5dT78Uyu
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  gatherit:
    build:
      context: ../Comulator
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://rabbituser:rabbitpass@rabbitmq:5672/%2f
      - KAFKA_URL=kafka:9092

  postgres-jobads:
    build:
      context: ../Database
      dockerfile: Dockerfile-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pL5dT78Uyu
      POSTGRES_DB: postgres
    ports:
      - "5400:5432"
    volumes:
      - database-postgres-jobads:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-scheduler:
    build:
      context: ../scheduler/database
      dockerfile: Dockerfile-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jad21D10cazX
      POSTGRES_DB: postgres
    ports:
      - "5401:5432"
    volumes:
      - database-postgres-scheduler:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  scheduler:
    build:
      context: ../scheduler
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    depends_on:
      postgres-scheduler:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:jad21D10cazX@postgres-scheduler:5432/postgres
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://127.0.0.1:8101/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  pracuj-scraper:
    build:
      context: ../scrapyard/pracuj-scraper
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    depends_on:
      rabbitmq:
        condition: service_healthy
      scheduler:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://rabbituser:rabbitpass@rabbitmq:5672/%2f
      - RABBITMQ_EXCHANGE=mapping_exchange
      - RABBITMQ_ROUTING_KEY=mapping
      - SCHEDULER_URL=http://scheduler:8101/register
      - SCRAPER_ENDPOINT=http://pracuj-scraper:8800/scrap
      - ASPNETCORE_URLS=http://+:8001
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://127.0.0.1:8800/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  justjoinit-scraper:
    build:
      context: ../scrapyard/justjoinit-scraper
      dockerfile: Dockerfile
    ports:
      - "8801:8801"
    depends_on:
      rabbitmq:
        condition: service_healthy
      scheduler:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://rabbituser:rabbitpass@rabbitmq:5672/%2f
      - RABBITMQ_EXCHANGE=mapping_exchange
      - RABBITMQ_ROUTING_KEY=mapping
      - SCHEDULER_URL=http://scheduler:8101/register
      - SCRAPER_ENDPOINT=http://justjoinit-scraper:8801/scrap
      - "API_URL=https://api.justjoin.it/v2/user-panel/offers/?&sortBy=published&orderBy=DESC&perPage=100&salaryCurrencies=PLN&page="
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python -c "import urllib.request; urllib.request.urlopen(''http://127.0.0.1:8801/healthcheck'')" || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  theprotocolit-scraper:
    build:
      context: ../scrapyard/theprotocolit-scraper
      dockerfile: Dockerfile
    ports:
      - "8802:8802"
    depends_on:
      rabbitmq:
        condition: service_healthy
      scheduler:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://rabbituser:rabbitpass@rabbitmq:5672/%2f
      - RABBITMQ_EXCHANGE=mapping_exchange
      - RABBITMQ_ROUTING_KEY=mapping
      - SCHEDULER_URL=http://scheduler:8101/register
      - SCRAPER_ENDPOINT=http://theprotocolit-scraper:8802/scrap
      - "API_URL=https://apus-api.theprotocol.it/offers/_search?orderby.field=Relevance&pageSize=50&pageNumber="
      - "TP_XSRF_TOKEN=CfDJ8Ezt3dO9bWlKhqfe7qrrhyPvO6t6ZijadQv4THIqVdKxlCp4mMH-F3FONNdSLgOHgfo78klmEG20uB-_kU-zrmYXLFjmMQJ3bXKs5rW57coe0sEj3z5Ss5yVg6diJXTJ08zxPYL_cCwP4wvlfM65PHI"
      - "TP_COOKIE=gp__cfXfiDZP=98; cp_core=1; cp_personalized=1; cp_comfortable=1; cp_advertisement=1; cp_watch=1; cp_social=1; cookiesPolicy=v3; gptrackCookie=7d5356a2-faa1-4765-y7ce-58e3ed72d307; gp_tr_gptrackCookie=7d5356a2-faa1-4765-y7ce-58e3ed72d307; _gcl_au=1.1.1802970034.1741947874; _ga=GA1.1.1648334186.1741947875; _rdt_uuid=1741947874374.6b6a3822-6478-4663-b9ab-0168ac19647f; cto_bundle=9OiDOV9JcDB6N3NoSWpYeWVtJTJGNjFMUDBQR1RxcGt5SXlRSWxJUFhQRDlyWlhDcG9VMnVCV2lHTG11R055U0dBM25ncURjMEhCZ2owcVdsMjlnTjJzUDgxTXRTVzBNd204a1hXakklMkJBV01EQjZPczd3NWlYJTJCZkh3NExqWGpzMk4xJTJGVUtoc29xalRBaUtVRlFGN00wWm9mUkdNUDJkclMxNGp1Q3AzdTBDc2RsejI5MCUzRA; _uetvid=86d1b75000be11f0ad5a8f9d8afb3504; _fbp=fb.1.1741947875887.630211002633872631; _hjSessionUser_2833973=eyJpZCI6IjlkZTA4NTY5LWI5NDctNWVhMi1hZDMwLWQzNGVkNDdkZWFmMiIsImNyZWF0ZWQiOjE3NDE5NDc4NzU3NzIsImV4aXN0aW5nIjp0cnVlfQ==; __gfp_64b=BmwhaK7QpOXKyNFxaBoQ.6TGFbUnZcxzaQR79ZfaZBz.L7|1741947879|2|||8:1:32; _tt_enable_cookie=1; _ttp=01JPA2YYGG8983RD98609KJCHP_.tt.1; _ga_Z6EL58B8FL=GS1.1.1742001812.2.0.1742001812.60.0.0; _stemantiforgery=CfDJ8Ezt3dO9bWlKhqfe7qrrhyPnUJ5wY-AmijqT8j1EM8oYoDOngY1iJE1KhHI97Uf8uQf483GhLk60I0UT7Qw7bonu4PlSP_QTk_Qiu6oz4ke9DVd4h56aDgWH8b9RlfSmQVa3dBNE8FUlq0NCXCrHnZM; _cfuvid=cnleh8PrJPOxu3uEMRnY5yVRnVko.D99bAXYdnJ6O14-1743466288141-0.0.1.1-604800000; gp_ab__offerview__28=B; __cf_bm=kIic3bB6rPIfZqzXEbCh.aJwDWmPSe4R_lhlOrjALyQ-1743540892-1.0.1.1-O7PVgyUU8MXzNzXBKP_8rawxbcDZdfjLo26CKYvp9ZwAtP11dJhzbBaJRCvepcm8YP7iR.MynOAuX7ZYmk4EgX6vyboD81iwi7e6iw6w2FE; startquestion-session=%7B%22expirationDate%22%3A1743544490591%2C%22data%22%3A%7B%22pageTime%22%3A3570%2C%22numberOfVisitedPages%22%3A13%7D%7D; XSRF-TOKEN=CfDJ8Ezt3dO9bWlKhqfe7qrrhyPvO6t6ZijadQv4THIqVdKxlCp4mMH-F3FONNdSLgOHgfo78klmEG20uB-_kU-zrmYXLFjmMQJ3bXKs5rW57coe0sEj3z5Ss5yVg6diJXTJ08zxPYL_cCwP4wvlfM65PHI; gp_tr_gptrackPVID=e95e3589-2d85-405d-a9f4-dcbe2b59d2d7; gptrackPVID=7fcd27ef-2dd5-4bd1-y157-d51d8885a97e"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python -c "import urllib.request; urllib.request.urlopen(''http://127.0.0.1:8802/healthcheck'')" || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  binder:
    build:
      context: ../binder
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-jobads:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://rabbituser:rabbitpass@rabbitmq:5672/%2f
      - RABBITMQ_QUEUE_NAME=MappingQueue
      - RABBITMQ_CONSUMER_TAG=binder
      - DATABASE_URL=postgres://postgres:pL5dT78Uyu@postgres-jobads:5432/postgres
      - RUST_LOG=info

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
      RABBITMQ_DEFINITIONS_FILE: "/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database-postgres-jobads:
  database-postgres-scheduler:
  rabbitmq-data:
