name: Python

on:
  push:
    branches: ["master"]
    paths:
      - "scrapyard/justjoinit-scraper/**"
      - "scrapyard/pracuj-scraper/**"
      - ".github/workflows/python.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "scrapyard/justjoinit-scraper/**"
      - "scrapyard/pracuj-scraper/**"
      - ".github/workflows/python.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scraper: [justjoinit-scraper, pracuj-scraper]
    defaults:
      run:
        working-directory: scrapyard/${{ matrix.scraper }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"
          cache-dependency-path: scrapyard/${{ matrix.scraper }}/requirements.txt
      - name: Install ruff
        run: pip install ruff
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: ruff check .
